### ISSUE TITLE
Google API language support Laos is missing

### ISSUE THREAD

**Issue by minhto2811** [markokosticdev/cloud_text_to_speech_flutter#8]
![image](https://github.com/user-attachments/assets/7fef987e-dc94-4598-979e-e07453870c4a)
I see google docs support laos, but when I get the list I don't see it.
![image](https://github.com/user-attachments/assets/f7f04a11-c621-4b00-be35-8e3332db63f0)
Can you solve this problem? I can't complete my project with this problem.
If it was my fault, I sincerely apologize. Thanks.

**Comment by markokosticdev** [comment]
Have you resolved your issue

**Comment by minhto2811** [comment]
Sorry for the late reply. I use another voice like ar-AF or vi-VN instead of lo-LA(Laos) it still works. But for Khmer(km-KH) it also lacks voice and I use other voices instead but the result is not as expected, when playing the voice it is silent. Can you try it?
